#cargo-features = ['named-profiles']
[package]
name = "untitled"
version = "0.1.0"
authors = ["liushan <shan.liu@msn.com>"]
edition = "2018"

#[profile.release]
#panic = "unwind"


[dependencies]
futures="0.3"
actix-web = "3"
actix-files = "0.3"
actix-session = "0.4"
actix-utils = "2"
env_logger = "0.8"
serde="1.0.118"
sqlx = { version = "0.4.1", features = [ "mysql","runtime-tokio-native-tls"] }